#!/usr/bin/env node
// Survey authentic island terrain heights from the running game.
//
// The renderer rebuilds a 9-entry terrain-profile table at $7A8B every
// main-loop iteration: the ground height (in altitude/4 units) under the
// helicopter's footprint, which the landing logic at $8A7A compares
// against.  Calibration (see PR notes): all 9 samples sit within ~2
// flight units of the position, sea reads 0, the BASE pad reads 2
// (= altitude 8, the landed template value), PEAK's plateau reads 6.
//
// This tool teleports the helicopter across every island's record
// bounding box (padded), lets the game run a few frames, and records
// max($7A8B[0..8]) per sample point — producing byte-accurate heightmaps
// without porting the 3D renderer.
//
// Output: src/island_heightmaps.js — rows of digit strings, one char per
// STEP x STEP cell, heights in altitude/4 units.

import { writeFileSync } from 'node:fs';
import { createMachine } from '../emu/machine.mjs';
import { ISLAND_DATA } from '../src/islands_data.js';

const STEP = 2;
const PAD = 4;            // survey margin around each record box
const SETTLE_FRAMES = 12; // > two main-loop iterations

const m = createMachine();
const st = m.cpu.getState();
st.pc = 0x8C87;           // cold entry
m.cpu.setState(st);

// Boot and take off so the game sits in its normal flying state.
for (let f = 0; f < 250; f++) m.runFrame();
m.setControls({ up: true });
for (let f = 0; f < 150; f++) m.runFrame();
m.setControls({ up: false });
for (let f = 0; f < 50; f++) m.runFrame();

// Long surveys accumulate game events (aircraft collisions, cyclone
// drift, deaths) that corrupt later probes.  Snapshot the healthy
// just-airborne machine and restore it for every island.
const memSnap = m.mem.slice();
const cpuSnap = m.cpu.getState();
function restore() {
  m.mem.set(memSnap);
  m.cpu.setState(cpuSnap);
}

function heightAt(x, y) {
  // Every probe runs on an identical, freshly-restored machine — long
  // surveys otherwise accumulate game events (deaths, cyclone drift)
  // that corrupt the renderer state.
  restore();
  m.mem[0x7500] = x & 0xFF; m.mem[0x7501] = (x >> 8) & 0xFF;
  m.mem[0x7502] = y & 0xFF; m.mem[0x7503] = (y >> 8) & 0xFF;
  m.mem[0x750D] = 60;       // high altitude: no terrain contact
  m.mem[0x7515] = 0;        // airborne
  m.mem[0x7514] = 0;
  for (let f = 0; f < SETTLE_FRAMES; f++) m.runFrame();
  return Math.max(...m.mem.slice(0x7A8B, 0x7A94));
}

// Reference point: PEAK's plateau reads 6.  Verified before and after
// every island; a mismatch means the machine degraded mid-survey.
const REF = { x: 582, y: 116, h: 6 };

const out = [];
let probes = 0;
const t0 = Date.now();
for (const d of ISLAND_DATA) {
  restore();
  if (heightAt(REF.x, REF.y) !== REF.h) {
    throw new Error(`reference probe wrong after restore, before ${d.name}`);
  }
  const x0 = d.x0 - PAD, x1 = d.x1 + PAD;
  const y0 = d.y0 - PAD, y1 = d.y1 + PAD;
  const w = Math.floor((x1 - x0) / STEP) + 1;
  const h = Math.floor((y1 - y0) / STEP) + 1;
  const rows = [];
  let maxH = 0;
  for (let j = 0; j < h; j++) {
    let row = '';
    for (let i = 0; i < w; i++) {
      const v = heightAt(x0 + i * STEP, y0 + j * STEP);
      row += v.toString(36);   // heights are small (<= ~17)
      if (v > maxH) maxH = v;
      probes++;
    }
    rows.push(row);
  }
  if (heightAt(REF.x, REF.y) !== REF.h) {
    throw new Error(`reference probe degraded during ${d.name} — survey invalid`);
  }
  out.push({ name: d.name, x0, y0, step: STEP, w, h, maxH, rows });
  console.error(`${d.name}: ${w}x${h} sampled, max height ${maxH} (${probes} probes, ${((Date.now()-t0)/1000).toFixed(0)}s)`);
}

const lines = [
  '// Auto-generated by tools/extract_heightmaps.mjs',
  '// Authentic per-island terrain heights surveyed from the running game',
  '// (renderer terrain table $7A8B; values are altitude/4 units, i.e.',
  '// ground altitude = value * 4).  Grid origin (x0,y0) in flight',
  '// coordinates, STEP-unit cells, one base-36 digit per cell.',
  '',
  'export const ISLAND_HEIGHTMAPS = [',
];
for (const o of out) {
  lines.push(`  { name: ${JSON.stringify(o.name)}, x0: ${o.x0}, y0: ${o.y0}, step: ${o.step}, w: ${o.w}, h: ${o.h}, rows: [`);
  for (const r of o.rows) lines.push(`    ${JSON.stringify(r)},`);
  lines.push('  ] },');
}
lines.push('];');
lines.push('');
writeFileSync(new URL('../src/island_heightmaps.js', import.meta.url), lines.join('\n'));
console.error(`wrote src/island_heightmaps.js (${probes} probes in ${((Date.now()-t0)/1000).toFixed(0)}s)`);
