#!/usr/bin/env python3
"""
Extract the 14-island record table at memory $F230 from the decrypted
Cyclone code (file loads at $5B00).

Record layout (20 bytes), decoded from the island-detection comparator at
$76E5 (the renderer/main-loop routine that turns the helicopter position
into the current-island record pointer at $7552/53):

  +0   posX HIGH byte (position page; comparator requires equality)
  +1   posY HIGH byte
  +2   xMin low byte   \  bounding box in flight coordinates:
  +3   xMax low byte    | match iff  xMin <= posX.lo <= xMax
  +4   yMin low byte    |        and yMin <= posY.lo <= yMax
  +5   yMax low byte   /  (max is inclusive via the DEC A trick at $7701)
  +6..+9   a second, inner box (same page bytes) — feature/landing area
  +10..+13 pointers/data for the 3D renderer (not decoded)
  +14,+15  width/height hints
  +16,+17  display-file address of the island's map-screen name label
  +18,+19  attribute/terminator area ($FF at +0 ends the table)

Earlier versions of this tool misread +0/+1 as a "shape code" — they are
the position page bytes.  Island world placement is now byte-exact.

Output: src/islands_data.js, consumed by the three.js world builder and
by the exact islandAt() port in src/rom-physics.js.
"""

from pathlib import Path
import json

HERE = Path(__file__).resolve().parent
DEC  = HERE.parent / "decrypted"
OUT  = HERE.parent / "src" / "islands_data.js"

# Island names in record order (name list at $6A50; pairing verified by
# probing the comparator in the emulator: the helicopter's start position
# (313,368) matches record 5 = BASE, (640,400) matches record 0 = BANANA).
NAMES = [
    "BANANA", "ORTE ROCKS", "KOKOLA", "LAGOON", "PEAK",
    "BASE", "GILLIGANS", "RED", "SKEG", "BONE",
    "GIANTS GATEWAY", "CLAW", "LUKELAND ISLES", "ENTERPRISE",
]

BASE = 0x5B00
TBL  = 0xF230
REC_SIZE = 20


def decode_df_addr(addr):
    """ZX display-file char address ($4000-$57FF) -> (col, row) on 32x24."""
    off = addr - 0x4000
    row = (off >> 11) * 8 + ((off >> 5) & 7)
    return off & 31, row


def main():
    data = (DEC / "cyclone_code_and_data.bin").read_bytes()
    off = TBL - BASE
    islands = []
    for i, name in enumerate(NAMES):
        rec = data[off + i * REC_SIZE: off + (i + 1) * REC_SIZE]
        xh, yh = rec[0], rec[1]
        x0, x1 = (xh << 8) | rec[2], (xh << 8) | rec[3]
        y0, y1 = (yh << 8) | rec[4], (yh << 8) | rec[5]
        ix0, ix1 = (xh << 8) | rec[6], (xh << 8) | rec[7]
        iy0, iy1 = (yh << 8) | rec[8], (yh << 8) | rec[9]
        pos = rec[16] | (rec[17] << 8)
        col, row = decode_df_addr(pos)
        islands.append({
            "name": name,
            "xPage": xh, "yPage": yh,
            "xMinLo": rec[2], "xMaxLo": rec[3],
            "yMinLo": rec[4], "yMaxLo": rec[5],
            "x0": x0, "x1": x1, "y0": y0, "y1": y1,
            "inner": [ix0, ix1, iy0, iy1],
            "wHint": rec[14], "hHint": rec[15],
            "col": col, "row": row,
            "raw": rec.hex(),
        })

    lines = [
        "// Auto-generated by tools/extract_island_table.py",
        "// Source: decrypted Cyclone ROM, island record table at $F230.",
        "// Bounding boxes are in flight coordinates and byte-exact: the",
        "// comparator at $76E5 matches posX/posY against (page, lo-range)",
        "// per axis.  See the extractor docstring for the full layout.",
        "",
        "export const ISLAND_DATA = [",
    ]
    for d in islands:
        lines.append(
            f"  {{ name: {json.dumps(d['name']) + ',':<19}"
            f" xPage: {d['xPage']}, yPage: {d['yPage']},"
            f" xMinLo: 0x{d['xMinLo']:02X}, xMaxLo: 0x{d['xMaxLo']:02X},"
            f" yMinLo: 0x{d['yMinLo']:02X}, yMaxLo: 0x{d['yMaxLo']:02X},"
        )
        lines.append(
            f"    x0: {d['x0']:>3}, x1: {d['x1']:>3},"
            f" y0: {d['y0']:>3}, y1: {d['y1']:>3},"
            f" inner: {d['inner']},"
            f" wHint: {d['wHint']}, hHint: {d['hHint']},"
            f" col: {d['col']}, row: {d['row']} }},"
        )
    lines.append("];")
    lines.append("")
    OUT.write_text("\n".join(lines))
    print(f"Wrote {OUT}\n")

    print(f"{'#':>2}  {'name':<15} {'X range':<12} {'Y range':<12} "
          f"{'size':<9} inner-box (contained?)")
    print("-" * 78)
    for i, d in enumerate(islands):
        contained = d['x0'] <= d['inner'][0] <= d['inner'][1] <= d['x1'] and \
                    d['y0'] <= d['inner'][2] <= d['inner'][3] <= d['y1']
        print(f"{i:>2}  {d['name']:<15} {d['x0']:>3}..{d['x1']:<6} "
              f"{d['y0']:>3}..{d['y1']:<6} {d['x1']-d['x0']:>3}x{d['y1']-d['y0']:<4} "
              f"{d['inner']} {'yes' if contained else 'NO'}")


if __name__ == "__main__":
    main()
