// Auto-generated by tools/extract_island_table.py
// Source: decrypted Cyclone ROM, island record table at $F230.
// Bounding boxes are in flight coordinates and byte-exact: the
// comparator at $76E5 matches posX/posY against (page, lo-range)
// per axis.  See the extractor docstring for the full layout.

export const ISLAND_DATA = [
  { name: "BANANA",           xPage: 2, yPage: 1, xMinLo: 0x5C, xMaxLo: 0xA8, yMinLo: 0x80, yMaxLo: 0xB8,
    x0: 604, x1: 680, y0: 384, y1: 440, inner: [626, 658, 412, 412], wHint: 13, hHint: 6, col: 15, row: 11 },
  { name: "ORTE ROCKS",       xPage: 1, yPage: 2, xMinLo: 0x88, xMaxLo: 0xD3, yMinLo: 0x00, yMaxLo: 0x39,
    x0: 392, x1: 467, y0: 512, y1: 569, inner: [414, 445, 540, 541], wHint: 12, hHint: 7, col: 14, row: 17 },
  { name: "KOKOLA",           xPage: 1, yPage: 0, xMinLo: 0x57, xMaxLo: 0xA1, yMinLo: 0x94, yMaxLo: 0xCC,
    x0: 343, x1: 417, y0: 148, y1: 204, inner: [365, 395, 176, 175], wHint: 12, hHint: 7, col: 8, row: 6 },
  { name: "LAGOON",           xPage: 0, yPage: 0, xMinLo: 0x74, xMaxLo: 0xCB, yMinLo: 0xB8, yMaxLo: 0xF0,
    x0: 116, x1: 203, y0: 184, y1: 240, inner: [138, 181, 212, 212], wHint: 16, hHint: 7, col: 2, row: 7 },
  { name: "PEAK",             xPage: 2, yPage: 0, xMinLo: 0x28, xMaxLo: 0x65, yMinLo: 0x58, yMaxLo: 0x90,
    x0: 552, x1: 613, y0:  88, y1: 144, inner: [574, 591, 116, 116], wHint: 10, hHint: 7, col: 16, row: 2 },
  { name: "BASE",             xPage: 1, yPage: 1, xMinLo: 0x1C, xMaxLo: 0x82, yMinLo: 0x50, yMaxLo: 0x88,
    x0: 284, x1: 386, y0: 336, y1: 392, inner: [306, 364, 364, 364], wHint: 20, hHint: 7, col: 6, row: 12 },
  { name: "GILLIGANS",        xPage: 1, yPage: 0, xMinLo: 0x1C, xMaxLo: 0x5E, yMinLo: 0x58, yMaxLo: 0x91,
    x0: 284, x1: 350, y0:  88, y1: 145, inner: [306, 328, 116, 117], wHint: 10, hHint: 7, col: 2, row: 2 },
  { name: "RED",              xPage: 1, yPage: 2, xMinLo: 0x78, xMaxLo: 0xB6, yMinLo: 0x40, yMaxLo: 0x78,
    x0: 376, x1: 438, y0: 576, y1: 632, inner: [398, 416, 604, 604], wHint: 9, hHint: 7, col: 13, row: 19 },
  { name: "SKEG",             xPage: 0, yPage: 2, xMinLo: 0x70, xMaxLo: 0xAD, yMinLo: 0x00, yMaxLo: 0x38,
    x0: 112, x1: 173, y0: 512, y1: 568, inner: [134, 151, 540, 540], wHint: 9, hHint: 7, col: 5, row: 17 },
  { name: "BONE",             xPage: 1, yPage: 0, xMinLo: 0xAC, xMaxLo: 0xFF, yMinLo: 0x7C, yMaxLo: 0xB4,
    x0: 428, x1: 511, y0: 124, y1: 180, inner: [450, 489, 152, 152], wHint: 15, hHint: 7, col: 15, row: 5 },
  { name: "GIANTS GATEWAY",   xPage: 1, yPage: 1, xMinLo: 0x98, xMaxLo: 0xCB, yMinLo: 0x0C, yMaxLo: 0x50,
    x0: 408, x1: 459, y0: 268, y1: 336, inner: [430, 437, 296, 308], wHint: 7, hHint: 10, col: 14, row: 9 },
  { name: "CLAW",             xPage: 1, yPage: 1, xMinLo: 0xC4, xMaxLo: 0xFD, yMinLo: 0xC0, yMaxLo: 0xFE,
    x0: 452, x1: 509, y0: 448, y1: 510, inner: [474, 487, 476, 482], wHint: 8, hHint: 8, col: 16, row: 15 },
  { name: "LUKELAND ISLES",   xPage: 0, yPage: 2, xMinLo: 0x30, xMaxLo: 0x6D, yMinLo: 0x30, yMaxLo: 0x6C,
    x0:  48, x1: 109, y0: 560, y1: 620, inner: [70, 87, 588, 592], wHint: 9, hHint: 8, col: 2, row: 19 },
  { name: "ENTERPRISE",       xPage: 0, yPage: 1, xMinLo: 0x44, xMaxLo: 0x8B, yMinLo: 0xB0, yMaxLo: 0xFB,
    x0:  68, x1: 139, y0: 432, y1: 507, inner: [90, 117, 460, 479], wHint: 11, hHint: 12, col: 4, row: 14 },
];
